"""Turn Bicep deployment outputs into a .env file for local runs.

    az deployment group show ... --query properties.outputs -o json \
        | python scripts/outputs_to_env.py

Only endpoints and names are written, never a secret: every service authenticates with
Entra ID, so there is nothing secret to copy. The file is still git-ignored, because it
describes one person's environment.
"""

import json
import sys

# Bicep output name -> environment variable read by src/api/core/settings.py
MAPPING = {
    "aiServicesEndpoint": "AZURE_OPENAI_ENDPOINT",
    "chatDeploymentName": "AZURE_OPENAI_CHAT_DEPLOYMENT",
    "embeddingDeploymentName": "AZURE_OPENAI_EMBEDDING_DEPLOYMENT",
    "cosmosEndpoint": "AZURE_COSMOS_ENDPOINT",
    "cosmosDatabaseName": "AZURE_COSMOS_DATABASE",
    "searchEndpoint": "AZURE_SEARCH_ENDPOINT",
    "storageBlobEndpoint": "AZURE_STORAGE_BLOB_ENDPOINT",
    "keyVaultUri": "AZURE_KEY_VAULT_URI",
    "apiUrl": "API_URL",
}


def main() -> int:
    outputs = json.load(sys.stdin)
    missing = [name for name in MAPPING if name not in outputs]
    if missing:
        print(f"missing deployment outputs: {missing}", file=sys.stderr)
        return 1

    print("# Generated by `make env` from the last infrastructure deployment. No secret here.")
    for output_name, variable in MAPPING.items():
        print(f"{variable}={outputs[output_name]['value']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
